apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
type: Opaque
data:
  GOOGLE_CLIENT_ID: NDc1NDg4MjczOTU2LXZxc2U4YTJxYzAxZjA5MjIwYTdwMXY2cWdpNXBmaDRvLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tCg==
  GOOGLE_CLIENT_SECRET: R09DU1BYLUJVT3NxV3kyOUxITnhDV00xNVFrQ2pKb09BZmUK
  OPEN_WEATHER_KEY: MmM4MWFmMjE0NGM0N2Y5YmZmMGJiN2IxYzhlNmE4MmMK