apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
      name: flask-app
  selector:
    app: flask-app
  type: LoadBalancer    